# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ab4844d6901002fd7a56e821233ec185be0e63b24a9ae6cd133d28f84f4fc511cc97e6cb6177fccc3700feb7b69d4cda6bfbd77d305432c7d642b75448e572

test:
  secret_key_base: 31bfdbd002adbd458bc932eae44439e5c7599058d3305f63162e4ada5adc062c7cc31af114d5e39c9bc9b526de3ea4d6d4b36d4a087e34c008c6246326d06989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
